### ISSUE TITLE
HT_DEBUG_PRINTF should log to a file

### ISSUE THREAD

**Issue by Honeybunch** [thirddegree/HatchitCore#25]
Since the console can fly by, especially during shutdown we should really have debug statements print to a file so we can review it later. Maybe even have a flag to allow a release build to log to a file in case we have problems in release?

**Comment by raselneck** [comment]
@Honeybunch I feel like there may have been something in class mentioned about this regarding one small addition / change for me to make? If not then this issue can be closed.
