### ISSUE TITLE
RefCountedResourceManager occasionally crashes on shutdown

### ISSUE THREAD

**Issue by Honeybunch** [thirddegree/HatchitCore#33]
Occasionally on shutdown I get an assert in the RefCountedResourceManager's destructor. Line 33 of ht_refcounted_resource_manager.h. 

It only happens on some shutdown sequences.

**Comment by ghost** [comment]
This generally happens because handles are holding on to each other and not releasing when the rest of the program releases the handles.  This assert should never be hit, and if it is, there's an issue with handles not releasing.
