### ISSUE TITLE
Empty guid cannot be accessed without static function

### ISSUE THREAD

**Issue by ghost** [thirddegree/HatchitCore#47]
No idea why the symbols aren't being found for `Guid::Empty`.  Any insight would be helpful.

**Comment by MattGuerrette** [comment]
It must be declared in the cpp as well. Like

`Guid Guid::Empty;`

**Comment by raselneck** [comment]
@MattGuerrette [It is](https://github.com/thirddegree/HatchitCore/blob/dev/source/ht_guid.cpp#L231).
